name: Pre Release
on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - 'v**'
      - 'ci'
  workflow_dispatch:

concurrency:
  group: pre-release
  cancel-in-progress: true

jobs:
  pre-release:
    name: Pre Release
    uses: ./.github/workflows/build.yml
    with:
      release-type: pre-release
